#inductive eq : (A : Set) -> (x : A) -> A -> Prop {
    eq_refl: (A : Set) -> (x : A) -> eq A x x,
}

#inductive nat : Set {
    O: nat,
    S: nat -> nat,
}

#definition add : (n : nat) -> (m : nat) -> nat {
    #match n {
        O => m,
        S p => S (add p m),
    }
}

#theorem nat_0_eq_0 : eq nat O O {
    eq_refl nat O
}

#theorem nat_1_eq_1 : eq nat (S O) (S O) {
    eq_refl nat (S O)
}
